### ISSUE TITLE
How to run your cpp program?

### ISSUE THREAD

**Issue by Abbyzlh** [marleyshan21/Batch-informed-trees#1]
I am trying to run your cpp program, but how to run it and is there any visualization in it?

**Comment by marleyshan21** [comment]
Hey, there are no visualizations for the cpp part yet. It is in the development phase. 
The python part is up and running.
But you could create a build folder in the cpp folder and cmake it.  That would help you run the unit test - but it wont be as fast as the python one. We are working on it.
